baseurl = "https://k-watanb.github.io/"
title = "ML戦記"
theme = "hugo_theme_robust"

googleAnalytics = "G-Q8JBWP2QFH" # Optional
disqusShortname = "XYW"
defaultContentLanguage = "ja-jp"

hasCJKLanguage = true
publishDir = "docs"

pygmentsCodefences = true
pygmentsUseClasses = true

[params]
    dateformat = "2006-01-02"
    copyrightYear = "2020-2021"

[params.posts]
    show_thumb_post = false
    toc = false

[params.author]
    thumbnail = "/images/author.jpg"
    name = "<a href ='/about/'>k-watanb</a>"
    description = "<p>名古屋で機械学習エンジニアやっとります。<br>I'm a machine learning engineer in Nagoya, Japan.</p>"
    # facebook = ""
    # twitter = "https://www.google.co.jp/"
    github = "https://github.com/k-watanb"

[outputs]
    page = [ "HTML", "AMP" ] # if you want AMP enable.
